# Generated by Django 6.0.2 on 2026-03-03 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create restaurant table if it doesn't exist
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS restaurant (
                    id SERIAL PRIMARY KEY, 
                    name VARCHAR(255) NOT NULL, 
                    cuisine_type VARCHAR(255), 
                    address TEXT, 
                    phone VARCHAR(20), 
                    opening_time VARCHAR(50), 
                    closing_time VARCHAR(50)
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS restaurant;"
        ),
        # Create menuitem table if it doesn't exist
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS menuitem (
                    id SERIAL PRIMARY KEY, 
                    name VARCHAR(255) NOT NULL, 
                    restaurant_id INTEGER NOT NULL
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS menuitem;"
        ),
        # Create orderitem table if it doesn't exist
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS orderitem (
                    id SERIAL PRIMARY KEY, 
                    price DOUBLE PRECISION NOT NULL, 
                    restaurant_id INTEGER NOT NULL
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS orderitem;"
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurant_id', models.IntegerField()),
            ],
            options={
                'db_table': 'menuitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('restaurant_id', models.IntegerField()),
            ],
            options={
                'db_table': 'orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=50, null=True)),
                ('closing_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver')], default='customer', max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
