# Generated by Django 6.0.3 on 2026-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_menuitem_orderitem_restaurant_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': True},
        ),
    ]
