# Generated by Django 6.0.3 on 2026-03-16 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_menuitem_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menuitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.menuitem'),
        ),
    ]
