# Generated by Django 6.0.3 on 2026-03-17 12:40

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_orderitem_menuitem'),
    ]

    operations = [
        # Tables are now handled in migration 0003
    ]
